[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
# Remove startCommand - let Dockerfile ENTRYPOINT handle it

[[deploy.volumes]]
mountPath = "/home/node/.n8n"