[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
startCommand = "n8n start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[mounts]]
mountPath = "/home/node/.n8n"
volumeName = "n8n_data"